import type { Metadata } from "next";

import { robotoFont, baloo2Font } from "@/utils/fonts";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${robotoFont.variable} ${baloo2Font.variable}`}>
			<body className="font-text text-base-text p-5">{children}</body>
		</html>
	);
}
